// ui/v1/src/app/shared/studio-card/studio-card.component.ts
import { Component, OnInit, Input, HostBinding } from '@angular/core';
import { Router } from '@angular/router';

import { StudioData } from '../../core/graphql-generated';

@Component({
  selector: 'app-studio-card',
  templateUrl: './studio-card.component.html',
  styleUrls: ['./studio-card.component.css']
})
export class StudioCardComponent implements OnInit {
  @Input() studio: StudioData.Fragment;

  // The host class needs to be card
  @HostBinding('class') class = 'dark card';

  constructor(
    private router: Router
  ) {}

  ngOnInit() {}

  onSelect(): void {
    this.router.navigate(['/studios', this.studio.id]);
  }

}

<a (click)='onSelect()' class="studio image" [style.background-image]="'url(' + studio.image_path + ')'"></a>
<div class="content">
  <div class="header">{{studio?.name}}</div>
  <div class="meta">{{studio?.scene_count}} Scenes</div>
</div>

// ui/v2.5/src/components/Studios/StudioCard.tsx
import { Card } from "react-bootstrap";
import React from "react";
import { Link } from "react-router-dom";
import * as GQL from "src/core/generated-graphql";

interface IProps {
  studio: GQL.StudioDataFragment;
}

export const StudioCard: React.FC<IProps> = ({ studio }) => {
  return (
    <Card className="studio-card">
      <Link to={`/studios/${studio.id}`} className="studio-card-header">
        <img className="studio-card-image" alt={studio.name} src={studio.image_path ?? ""} />
      </Link>
      <div className="card-section">
        <h5 className="text-truncate">{studio.name}</h5>
        <span>{studio.scene_count} scenes.</span>
      </div>
    </Card>
  );
};
