// ui/v2/src/components/performers/PerformerCard.tsx
import {
  Card,
  Elevation,
  H4,
} from "@blueprintjs/core";
import React, { FunctionComponent } from "react";
import { Link } from "react-router-dom";
import * as GQL from "../../core/generated-graphql";
import { TextUtils } from "../../utils/text";

interface IPerformerCardProps {
  performer: GQL.PerformerDataFragment;
  ageFromDate?: string;
}

export const PerformerCard: FunctionComponent<IPerformerCardProps> = (props: IPerformerCardProps) => {
  const age = TextUtils.age(props.performer.birthdate, props.ageFromDate);
  const ageString = `${age} years old${!!props.ageFromDate ? " in this scene." : "."}`;

  function maybeRenderFavoriteBanner() {
    if (props.performer.favorite === false) { return; }
    return (
      <div className={`rating-banner rating-5`}>
        FAVORITE
      </div>
    );
  }

  return (
    <Card
      className="grid-item"
      elevation={Elevation.ONE}
    >
      <Link
        to={`/performers/${props.performer.id}`}
        className="performer previewable image"
        style={{backgroundImage: `url(${props.performer.image_path})`}}
      >
        {maybeRenderFavoriteBanner()}
      </Link>
      <div className="card-section">
        <H4 style={{textOverflow: "ellipsis", overflow: "hidden"}}>
          {props.performer.name}
        </H4>
        {age !== 0 ? <span className="bp3-text-muted block">{ageString}</span> : undefined}
        <span className="bp3-text-muted block">Stars in {props.performer.scene_count} scenes.</span>
      </div>
    </Card>
  );
};

// ui/v1/src/app/shared/performer-card/performer-card.component.ts
import { Component, OnInit, Input, HostBinding } from '@angular/core';

import { PerformerData } from '../../core/graphql-generated';

@Component({
  selector: 'app-performer-card',
  templateUrl: './performer-card.component.html',
  styleUrls: ['./performer-card.component.css']
})
export class PerformerCardComponent implements OnInit {
  @Input() performer: PerformerData.Fragment;
  @Input() ageFromDate: string;

  // The host class needs to be card
  @HostBinding('class') class = 'dark card';

  constructor() {}

  ngOnInit() {}

}

<a [routerLink]="['/performers', performer.id]" class="performer image" [style.background-image]="'url(' + performer.image_path + ')'"></a>
<div class="content">
  <div class="header">
    <div class="ui heart rating">
      <i class="icon" [class.active]="performer.favorite"></i>
    </div>
    {{performer.name}}
  </div>
  <div class="meta">
    <div *ngIf="!!performer.birthdate" class="item">
      <span *ngIf="!!ageFromDate" class="date">{{performer.birthdate | age: ageFromDate}} years old in this scene.</span>
      <span *ngIf="!!ageFromDate === false" class="date">{{performer.birthdate | age}} years old.</span>
    </div>
    <div class="item">
      <span>Stars in {{performer.scene_count}} scenes.</span>
    </div>
  </div>
</div>
